### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#1037]
The projects feature of SDUCloud will allow a group of users to collaborate
together. This will span all the features of SDUCloud, including storage and
compute.

This issue will track the progress of the project feature. There will be links to
several sub-issues.

__This is a draft up for discussion.__

Projects play an important role in our compliance strategy on GDPR and
ISO-27001. Each project provide a clear view of the individuals involved and
their responsibility.

We define a project in SDUCloud as a set of users along with an associated
role. The following roles are available:

- __PI (Principal Investigator).__ Each project must have exactly one PI
attached to it. The PI serves as the primary contact point. The PI can
add/remove members from the project. The PI permissions is a superset of the
admin. A PI can transfer the role of PI to another member. This will
downgrade the current PI to admin.

- __Admin.__ A project can contain zero or more administrators.
Administrators can add/remove members from the project.

- __Data steward.__ Has the same permissions as a normal user. (Note: That is
how we define in the current documentation. We should find a more clear
distinction between data stewards and users.)

- __User.__ A normal user of the project. Normal users can interact with
files but cannot change the projects.

A project, like a normal user, has a set of resources attached to it. These
resources include: files, shared file systems and application results. The PI
is responsible for the resources in a project.

## Defining Project Context

A lot of features in SDUCloud will behave differently depending on your project.
We will deal with this by introducing an RPC header called `Project`. This
header should be present when a user wants to interact with a given project. If
a user wants to interact with their personal 'project' then this header should
not be present.

It is up to the service to determine what this header should be used for. Some
services might choose to ignore it. Other services might choose to reject the
call if no `Project` header is present.

To ensure this works well with caching we should add `Vary: Project` in HTTP
RPC.

## General Strategy for Permissions

Administrators can assign users to groups. Each group can have different
permissions on different resources. Resources can be fine grained. For
example, a resource could be a single folder in the project's files. This
would allow an administrator to give different permissions to different
groups. Each group could be acting on their own part of the project.

Resource managers will have a direct dependency on the project service. The
resource managers will ask the project API about the status of a member in a
project. This will include their role and which groups they belong to. The
resource managers themselves manage resources and permissions within a
project.

For improved performance we will allow services to cache results for a
minute. The cache is only a valid source of information when accepting a
request. Rejections should always double-check. This will allow a user to
perform requests they no longer have permissions for but limited to a minute
in time. In case of malicious use a minute is unlikely to make a significant
difference. A malicious user has likely had plenty of time to perform
malicious actions already.

## Project Related Features

In this is a list of project specific features the system requires:

- [x] Initial project abstractions
- [x] Support code for `Project` header in `service-common` (see above)
- [ ] Project management (#476)
- [ ] Project membership re-authorization (#687)
- [ ] Project share re-authorization (#688)
- [x] Backend functionality to send emails to users (Required for #687 and
  #688, depends on #837)

## Feature Overview

- [ ] __Activity:__ The full activity of any file related to the project
  folder is here. This list should also include which user performed a certain
  action. (#1040) 
- [ ] __Shares:__ Admins can change shares with the project. Normal users can
  only see a list of shares. (#1039)
- [ ] __Applications:__ All users can view the list of application runs. Only
  the user who started an application can interact with interactive
  applications. Admins can cancel any running job. (#1041)
- [ ] __Files:__ A single home folder owned by the project. Permissions
  controlled by the admins. (#1038)
- [x] __Shared file systems:__ Shared file systems should be usable by all
  users in a project. (#1042)
- [ ] __Trash:__ Follows same semantics as files. The service needs to put trash
  in the correct folder.
- [ ] __Notifications:__ The relevant parties should receive notifications.
  We should create utilities for dealing with this. Such as send a notification
  to all admins in a project.
- [ ] __Favorites:__ Are bound to the user performing the action. Not the
  project.
- [ ] __Search:__ File search should look for your projects and your home
  folder.
- [ ] __Accounting:__ Is bound to the project, not the user. All users can
  view general statistics. (See also #1041)
