### ISSUE TITLE
Projects: Storage

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#1038]
This issue tracks progress for the storage feature as it related to the
project feature (#1037).

This service will ignore the `Project` header. The frontend may use the active
context to determine which folder to show when going to "Files".

The storage-service acts as the primary resource controller of storage. As a
result, the storage-service will enforce authorization requirements, as it
currently does. We will expand the storage-service to understand projects,
roles, and groups.

Each project requires a "home" folder. We should create a home folder when a
user creates a project. The project service will notify us of these events
via the event stream. To avoid colliding with usernames we will put all
project home folders in `/projects/`. Currently a lot of code depends on all
home folders being in `/home/`. We will need to rewrite this code to also
work with `/projects`/.

All files in a project home folder will have an owner referring to the
project's PI (see below).

In the _current_ ACL system, each file can have an associated access control
list (ACL). Each entry in the ACL controls a single "entity's" access to a
file and all children of it. The entry contains a set of permissions that the
entry grants. A single ACL will apply to a complete sub-tree and not only
direct children.

We will expand the ACL system to support projects. To do this we will focus
on the definition of an "entity". In the current system an entity is a string
referring to the username of a user. The new definition will also cover
various definitions from projects. We define the new entity with the
following code:

```kotlin
sealed class Entity {
    data class User(val username: String) : Entity()
    data class ProjectAndRole(val projectId: String, val role: ProjectRole) : Entity()
    data class ProjectAndGroup(val projectId: String, val group: String) : Entity()
}
```

To remain backwards compatible we will continue to accept a string. In this
case it will still refer to a username (`Entity.User`). We can achieve this
with a custom Jackson deserializer.

This new setup means that a user can have more than one entity apply to them.
We will grant access to a resource if _any_ of the entries would allow it.

We will implement the project permissions for storage in a separate service.
This is the exact same approach currently used for shares. Only admins can
change permissions for a project. The storage service should assume an
implicit R+W entry for every project where the role is ADMIN/PI.

ACL and ownerName of files will also return an entity. In the case of a user
we will return a string to remain somewhat backwards compatible.

## Tasks

- [x] Create project home folders
- [ ] Rewrite code which depends on `/home` being the root of all file access.
  (Frontend and backend)
- [x] Expand the definition of an ACL entity
- [ ] Create a service for controlling project permissions
- [ ] Create a frontend for controlling project permissions
