### ISSUE TITLE
Projects: File shares

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#1039]
This issue tracks progress for the share feature as it related to the project
feature (#1037).

The share service will accept the "Project" RPC header. The share service
will only show shares valid for that context.

Shares are currently only private to a single user. This single user is able
to create/edit/view/accept/reject all the shares. In the case of user-to-user
shares this behavior will continue.

For projects only admins should be able to create/edit/accept/reject shares.
Normal users should be able to view a list of shares.

We will allow the following types of shares:

- Project-to-project
- Project-to-user
- User-to-project. This one is up for discussion, @bhjakobsen has expressed
  concern.
- User-to-user

For project-to-project users we allow sharing with the entire project. To
begin with we will not support more fine-grained sharing. More fine-grained
access is doable via the permission service for project's storage.

## Tasks

- [ ] Update the service to support projects
- [ ] Update the frontend to support project-to-project sharing
- [ ] Send notifications to admins when a project receives an incoming share
