### ISSUE TITLE
Projects: Applications

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#1041]
This issue tracks progress for the application feature as it related to
the project feature (#1037).

This service will accept the "Project" RPC header. The service will only use
results relevant to the project.

This issue will focus only on how to handle application runs
(orchestrator/k8). For a discussion on ACLs on applications see #848.

The application orchestration should only change in small ways. Below is a
list of changes required.

## Tasks

- [ ] Enable accounting for projects
- [ ] Add creator to accounting
- [ ] Update jobs folder location
- [ ] Allow project ownership of a job
- [ ] Allow admins to cancel any project job
- [ ] Ensure only the creator can use interactive jobs
