### ISSUE TITLE
Projects: Shared file systems

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#1042]
This issue tracks progress for the app-fs feature as it related to 
the project feature (#1037).

This service will accept the "Project" RPC header. The service will only use
results relevant to the project.

This service needs to have its permission model updated to support projects.

## Tasks

- [ ] Allow ownership of app-fs to be a project
- [ ] Create a permission model for projects. The permission model will mirror
  the storage service's approach.
- [ ] Create UI for permissions
