### ISSUE TITLE
[docs] Documentation

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2762]
This epic tracks the progress of writing documentation for the next release of UCloud (2021.3.0). The progress of the release is also tracked in #2831.

The documentation which this epic tracks can be found here: https://github.com/SDU-eScience/UCloud/tree/storage/docs/developer-guide

The documentation of the next release will build on top of the code-generation already done on the `master` branch.

We will structure the documentation around the network level API of UCloud. Each page of the documentation will describe a single RPC namespace. Each RPC namespace covers the following sections:

- Short, single line description.
- Short rationale for the feature. Intended to motivate why the feature exists and primary use-cases.
- (Optional) Further explanations about the feature
- Examples, generated from the code. The examples will show how to use the API in multiple ways. This includes: 
  - Usage through Kotlin (Backend and Integration Module),
  - TypeScript (Frontend)
  - Curl (raw network)
  - Visual diagrams
- Technical reference of every RPC
- Technical reference of every data model

We structure the documentation into the following sections. Each section contain sub-sections and eventually descriptions of the RPC namespaces involved.

The following checklist describes the progress of writing the documentation:

- Accounting and Project Management
   - [ ] Projects (Partially completed)
   - [x] Providers
   - [x] Products
   - [x] Accounting
   - [ ] Grants (Partially completed)
- Orchestration of Resources
   - [x] Introduction to Resources
   - [ ] Storage
      - [x] Drives
      - [x] Files
      - [x] Shares
      - [x] Metadata
      - [ ] Provider APIs (Partially completed)
   - [ ] Compute
      - [x] Application Store
      - [x] Jobs
      - [x] Public IPs
      - [x] Public Links
      - [x] Software Licenses
      - [ ] Provider APIs (Partially completed)
- Core
   - [x] Core Types (Partially completed)
   - [x] API Conventions
   - [x] Users
   - [x] Monitoring and Alerting (Partially completed)
   - [x] Communication
- Built-in Provider
   - [x] UCloud/Storage (Partially completed)
   - [ ] UCloud/Compute (Partially completed)

**Comment by DanThrane** [comment]
Closing this issue for now. We will continue to improve documentation as part of our normal development process.
