### ISSUE TITLE
[fault-injection] Fault injection for UCloud

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#3872]
Failure injection can be a useful tool in improving  the stability of the service. It should be possible to tell any internal and external component to fail in various ways. Examples of components in which failure injection makes sense:

- Databases, such as Postgres or Redis
- The network (e.g. RPC and HTTPS communication)
- Compute systems, such as Kubernetes and Slurm
- Storage systems
- External programs (e.g. Slurm CLI)

The errors produced should be both soft (e.g. slow) and hard failures (e.g. crashes). The following is a list of example failure scenarios:

- Produce an error of a given type
- Simulate that the service is unavailable
- Simulate the operation being slow
- Simulate malformed input/output

It must be possible to configure the fault injection via an RPC API. This is a hard requirement for the integration testing protocol. This should allow the client to describe when and how the failure should occur. This API must be available only when it explicitly turned on.

The most obvious implementation strategy involves implementing a middleware. This middleware should intercept all calls t o the systems we wish to inject faults into. 

If relevant, the injection system should notify RPCs about injected failures. Clients can inspect injected faults in the HTTP response headers. This will allow the UI to show an indicator telling the developer that a fault has happened. This feature also makes it possible to have a "chaos mode". In this mode, a set of failures will start occurring at random occasions. This will help us test the resilience of the user-interface. This chaos mode should be configurable and somewhat predictable. It should be possible to re-produce error scenarios that were randomly generated. 

The API has the following model:

```kotlin
data class InjectedFault(
    // The system describes which code should be affected by this
    val system: System,

    // The condition, naturally, tells the system when it should occur
    val condition: Condition,

    // And the fault tells the system what should happen when it does occur
    val fault: Fault
)
```

A condition is most naturally described using the following "AST":

```kotlin
typealias Condition = Conjunction

sealed class Term

data class Conjunction(
    val terms: List<Disjunction>
) : Term()

data class Disjunction(
    val terms: List<Term>
) : Term()

data class Negate(val conjunction: Conjunction) : Term()
sealed class Comparison : Term() {
    abstract val property: String
} 

data class StringComparison(
    override val property: String,
    val op: Op,
    val rhs: String,
) : Comparison() {
    enum class Op {
        EQUALS,
        EQUALS_IGNORE_CASE,

        NOT_EQUALS,
        NOT_EQUALS_IGNORE_CASE,

        STARTS_WITH,
        STARTS_WITH_IGNORE_CASE,

        ENDS_WITH,
        ENDS_WITH_IGNORE_CASE,

        CONTAINS,
        CONTAINS_IGNORE_CASE,

        // In this case RHS is a regex
        MATCHES_REGEX
    }
}

data class IntComparison(
    override val property: String,
    val op: Op,
    val rhs: Long
) : Comparison() {
    enum class Op {
        EQUALS,
        NOT_EQUALS,

        LESS_THAN,
        LESS_THAN_EQUALS,

        GREATER_THAN,
        GREATER_THAN_EQUALS,
    }
}

data class FloatComparison(
    override val property: String,
    val op: Op,
    val rhs: Double
) : Comparison() {
    enum class Op {
        EQUALS,
        NOT_EQUALS,

        LESS_THAN,
        LESS_THAN_EQUALS,

        GREATER_THAN,
        GREATER_THAN_EQUALS,
    }
}

data class BooleanComparison(
    override val property: String,
    val comparisonValue: Boolean
) : Comparison()
```

Faults are system dependent. The following sections will give some examples.

## RPC system faults

Timeout/delay: Make the response slow. It should be configurable how slow.

Fixed response: Return a specific response. This includes the status code, headers and payload.

TLS fault: Fake an expired or invalid certificate. It can be configurable which type of failures.

Connection failure: Fake a connection failure (e.g. simulate a firewall blocking the connection).

Response failure: send the request but fail at forwarding the real response. Instead, the client will receive a "Bad gateway" response after some delay.

## Postgres faults

Timeout/delay: Make the response slow. It should be configurable how slow.

Error: Causes a configurable error response.

Connection failure: Simulates a failure to connect to the database.

## Distributed lock faults

Timeout/delay: Make the response slow. It should be configurable how slow.

Error: Causes a configurable error response.

## Event stream faults

Timeout/delay: Make the response slow. It should be configurable how slow.

Receive double messages: This simulates that the code receives two messages instead of a single. This helps the debug issues arising from the fact that we do not have guaranteed one-time delivery. 

Fail to send: Produce an error message when sending.

Fail to receive: Produce an error message when receiving a message.

## Kubernetes faults

Timeout/delay: Make the response slow. It should be configurable how slow.

Error: Causes a configurable error response.

Connection failure: Simulate a failure to connect.

Fake resource status: This will modify the YAML resource of a real Kubernetes resource. This can help us simulate specific failures in the system.

## File-system faults

Timeout/delay: Make the response slow. It should be configurable how slow.

Hard failure to read/write: This will cause an error on all calls.

Flakey: This will cause some calls to randomly fail.

## Slurm faults

Timeout/delay: Make the response slow. It should be configurable how slow.

Connection failure: Simulate a failure to connect to Slurm.

Error: Causes a configurable error response.

**Comment by DanThrane** [comment]
I have implemented the minimum code required for the system on `devel-fault-injection`. What is left is to now:

- [ ] Implement the different faults for our systems
- [ ] Integrate this with our testing
- [ ] Integrate this with our user-interface
- [ ] (Use this for something)
