### ISSUE TITLE
(More) UI-redesign issues

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#4050]
- [x] The confirmation buttons are no longer styled correctly (as of 30/8 merge)
- [x] Viewing wallets that exceed a certain value aren't correctly truncated - Actually, thousand-separators were calculated wrong
- [x] For long enough resourcebrowser-lists, clicking the lower entries will select one a few rows above. Clicking one seems to affect behavior of others. This seems to be affected by which size resource browser was initialized first, through some stateful values associated with the class.
- [x] File popup when selecting file to add to job is not backwards navigable. I can select a file or go into folder, but I cannot go back. Also, different drives cannot be selected.
- [x] Some onClick handlers can be mounted twice, if modal shows table, for instance.
- [x] Grants ingoing/outgoing are not used meaningfully. Nothing is shown when Type N project, for instance.
- [x] Remove top line if not showing rowtitles
- [x] Truncate titles for titles in resource browser
- [x] Remove recent notifications from dashboard
- [x] Move log out in user menu
- [x] "Updated avatar" is prompted for the wrong call.
- [x] ContextSwitcher - Missing top and bottom padding
- [x] ContextSwitcher/ProductSelector - Allow arrow-key navigation
- [x] ContextSwitcher - Remove "My Workspace" as a something that's always shown
- [x] Jobs - Remove "Load parameters..." text from job creation
- [x] Jobs - Padding in cards missing
- [x] Jobs - Missing header in JobSelector
- [x] Jobs - Documentation icon should have a tooltip
- [x] Remove default margin for headings
- [x] Use button in modals are shown along with other properties, also shows rowtitle
- [x] Sidebar - every button should navigate to - something -
- [x] ResourceBrowser - change padding for row titles and more operations
- [x] FileOperations - Remove "Add to sync" for current directory.
- [x] FileOperations - Remove "beta" text
- [x] Job View - Change padding (Heading margin thing, essentially)
- [x] Dashboard/JobView inconsistent font-size
- [x] Remove references to old BrowseComponent
- [x] Subprojects uses the old list
- [x] Date in notifications are right next to the title
- [x] Project invites tooltip is outdated
- [x] "Price per hour" is missing space
- [x] Make sidebar only sticky when user clicks "stick" button
- [x] For simple jobs view, show only date or time to save space
- [x] ContextMenu has an offset on the Job View page (https://github.com/sdu-eScience/uCloud/issues/4050#issuecomment-1746402149)
- [x] ProvidersBrowse (Admin) still uses the old browse component
- [x] LicenseBrowse still in use for app-widgets
- [x] NetworkIPBrowse still in use for app-widgets
- [x] The Notifications, Usermenu and support box seem to have different `left` and `bottom` values
- [x] React Markdown 9.0.0 renders quoted tags in the wrong way (https://github.com/SDU-eScience/UCloud/issues/4050#issuecomment-1756978740)
- [x] Share state/rights are invisible in light mode
- [x] Public IP/Public Links browser should show what app is using them, if any
- [x] Allow selecting workspace when FileBrowse is embedded
- [x] Key event propagates from Clickable Dropdown (again)
- [x] Shared with me can show defaultAvatar when a custom one exists.
- [x] FileBrowse isn't consistently fetching files when embedded (Always after the first time?)
- [x] #4081
- [x] File Shares navigation uses wrong target path
- [x] Share Properties is not available
- [x] Tooltips can persist across pages.
- [x] Context menu remains open on navigation forward or backward using keyboard
- [x] #4071
- [x] #4076 
- [x] #4077
- [x] #4080
- [x] My Workspace files can't be reached in file selector, if user has an active project.
- [x] [Coloring issues for "Newer version available"](https://github.com/SDU-eScience/UCloud/issues/4050#issuecomment-1790694142)
- [x] Empty resource-list position for non-default (embedded/modal) ResourceBrowser
- [x] Refresh is memoized in a callback, making it stick between pages
- [x] Sidebar running job is not in sync with user actions
- [x] Max amount of drives in modal dropdown is limited to 10, set to 250
- [x] Provider Cards are ugly
- [x] Aspect ratio for UCloud logo used in Provider cards are wrong
- [x] Set `maxHeight` to ContextMenu, in cases of too many entries (e.g. drives in FileSelection modal)
- [x] Avatars in 'Shared by me' aren't updated correctly.

**Comment by Tiggles** [comment]
Part 1 in #4033

**Comment by xiroV** [comment]
**Disclaimer:** Some of the following points are my personal opinion, and should probably be 
discussed before any action is taken.

I've tried to update the list according to the state of the front-end which is currently deployed on dev.

### General Comments

 - [ ] Keyboard shortcuts should not be visible on buttons.
   - Could be to shown on hover/tooltip instead. An overview of available shortcuts could be 
     shown by pressing "?".
 - [ ] Resource tables should have column headers. Sorting by column should be done by clicking on of 
   the columns.
 - [ ] Missing hover effect on buttons, links, application cards, etc.
 - [ ] Font sizes vary too much.
 - [ ] Filters/sort-by/right-click drop-down menus:
   - [ ] Entries should only show hover effect when hovering, but still shows if cursor is not inside 
     the drop-down.
   - [ ] Keyboard shortcuts should be styled more discreetly. Mayby like Github styles keyboard 
     shortcuts (press `?` on any page).
 - [ ] Checkboxes could be slightly smaller.
 - [ ] Clicking outside the input field during inline creation/renaming triggers the request to the 
   backend, even if the input field is empty.
 - [ ] There probably shouldn't be a border on the input field during inline creation of resources 
   (most likely my fault).



### Project Switcher

 - [ ] Width of name of selected project should be more dynamic such that projects with long names 
   are not clipped too short and projects with short names doesn't leave too much white-space 
   between the name and the arrow. Projects with too long names should still be clipped though.
 - [ ] There could be slightly more space between rows (padding) in the list of projects.
 - [ ] Menu opens where cursor clicks. A fixed position would be better.


### Sidebars

#### Runs

 - [ ] Icons should be white under "Running jobs" probably.

#### Notifications menu

 - [ ] Missing spacing between notifications (or remove border radius?).
 - [ ] Does not close when clicking on user-menu or support form.

#### Support Form Modal

 - [ ] Cursor should not be *pointer* on the box.
 - [ ] FAQ and Documentation links should have hover effect. Currently only the Documentation icon 
   have a hover effect.
 - [ ] Subject should not be a textarea, but input field (currently it is resizable).


#### User menu

 - [ ] Missing hover effect.
 - [ ] Weird spacing between entries.
 - [ ] Menu should close when clicking on entries/links.

   
### Pages

#### `/app/dashboard`

 - [ ] Needs a bit more spacing between headline/project-switcher and top cards.
 - [ ] Date/time column breaks to multiple lines. Not sure if intentional?
 - [ ] Grant applications card:
   - [ ] Entries are selectable, but there are no actions.
 - [ ] Providers card:
   - [ ] *Connect with the services*-text should be removed.
   - [ ] Names of providers are too large.

#### `/app/users/avatar`

 - [ ] The drop-downs should not be full-width, and they use the old style.

#### `/app/providers/overview`

 - [ ] Icons are too large.
 - [ ] Uses old style of cards.

#### `/app/project/grants/ingoing/`

 - [ ] Size of refresh icon (next to project switcher) is different than on Dashboard.

#### `/app/project/allocations/`

 - [ ] Missing padding in cards.
 - [ ] In general needs a style-review.

#### `/app/jobs`

 - [ ] Size of refresh icon (next to project switcher) is different than on Dashboard
 - [ ] Search-field moves other components (probably because I restyled the input field).
 - [ ] Missing spacing between filters makes them look cluttered.

#### `/app/providers/connect`

 - [ ] Missing top spacing, and maybe headline.

#### `/app/drives/`

 - [ ] Too much spacing to the right of date column?
 - [ ] Input box probably shouldn't be visible on creation and rename.
 - [ ] Delete confirmation modal needs spacing and/or restyling.

 
#### `/app/files/`

 - [ ] Button text color is wrong for *Create folder*. Maybe background is wrong too? (light-mode)
 - [ ] Button text not able to fit in *Create folder* button.
 - [ ] Not entirely clear what the edit icon is for.
 - [ ] *Empty trash* button is missing from Trash folder.
 - [ ] Drop-down in "Change sensitivity" uses old style.
 - [ ] Move to Trash-button in kebab menu is styled wrong.
 - [ ] Unable to select drive in Move-to and copy-to modal?
 - [ ] Favoriting a file does not update *Favorite files* in 2nd sidebar.
 - [ ] Create Link button in Share-modal should be centered.


#### `/app/jobs/`

 - [ ] Too much spacing to the right of date column?
 - [ ] "Stop" job button needs styling. Black icon and white text (in light mode). Both in drop-down 
   and in action bar.


#### `/app/admin/userCreation`

 - [ ] Missing spacing below input fields.

#### `/app/admin/news`

 - [ ] Missing spacing between input fields.
 - [ ] Date-pickers needs styling.
 - [ ] Headline *News* needs spacing from left?
 - [ ] Missing styling of *Edit* and *Preview* buttons.
 - [ ] There are two empty input-fields for each news post in the list?
 - [ ] Size of *Posts* headline is too small headline is too small.


#### `/app/news/list/`

 - [ ] Needs restyling in general.

#### `/app/shares`

 - [ ] Old filters still shown.
 - [ ] Needs restyling in general.

#### `/app/project/resources/`

 - [ ] Old filters still present?
 - [ ] Needs restyling in general.


#### Resource lists (`public-links`, `licenses`, `public-ips` and `ssh-keys`)

 - [ ] Creation is broken for public-links (request fails).

#### Resource properties page

 - [ ] Icon is too large.
 - [ ] Icon does not align with title.
 - [ ] Generally needs some restyling. Especially font-sizes in the cards.

**Comment by hschu12** [comment]
Attempted to make a new application for my workspace and filled out a request for 50 CPU hours.
Fronted rejects with a "At least one resource field must be non-zero."

**Comment by hschu12** [comment]
File popup when selecting file to add to job is not backwards navigable. I can select a file or go into folder, but I cannot go back

**Comment by Tiggles** [comment]
> Attempted to make a new grant application for my workspace and filled out a request for 50 CPU hours. Fronted rejects with a "At least one resource field must be non-zero."

Fixed

**Comment by Tiggles** [comment]
Uploading Screen Recording 2023-10-04 at 10.35.30.mov…

**Comment by Tiggles** [comment]
ContextMenu has an offset on the Job View page
https://github.com/SDU-eScience/UCloud/assets/7610257/5bbd71bb-7f9e-4097-8276-ba4bf35bcfb6

**Comment by DanThrane** [comment]
Rights in shares are invisible in light mode
<img width="1213" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/207000d9-0e1b-4629-8f34-d0e2f26066ae">
<img width="1207" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/5354bd33-1193-42e3-89e6-58afea11d5af">

**Comment by DanThrane** [comment]
<img width="1000" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/3e0dfeb3-5ad5-4547-ad76-ee01d3d009e6">

**Comment by Tiggles** [comment]
> <img alt="image" width="1000" src="https://user-images.githubusercontent.com/1782437/274187111-3e0dfeb3-5ad5-4547-ad76-ee01d3d009e6.png">

In what context is this shown? Job Results?

**Comment by Tiggles** [comment]
Dark theme uses two different colors. Both are white with light theme.
<img width="418" alt="Screenshot 2023-11-02 at 14 07 31" src="https://github.com/SDU-eScience/UCloud/assets/7610257/e263012d-39df-42d5-9149-3680fbdc1336">

**Comment by Tiggles** [comment]
Adding notes to fix context-handler issues:
- Seems some event handlers aren't correctly set, maybe left over from a different component. Can that even happen?
- Clicking above or below a row can open a context menu with different options. Seems like this menus handlers sometimes are populating the actual functionality.

**Comment by Tiggles** [comment]
Found the sinner for wiiiiiiide screen issue
<img width="943" alt="Screenshot 2023-11-13 at 16 01 29" src="https://github.com/SDU-eScience/UCloud/assets/7610257/396dafb4-7141-4fbe-a602-24c564cfbb9b">

**Comment by Tiggles** [comment]
I have no idea where this is coming from.

**Comment by DanThrane** [comment]
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/1d51f0d8-8a67-43ad-bd61-41cbba563ca1">

Clicking the project invite link notification leads to a not found page. @Tiggles, can you check this and other dead links in notifications?

**Comment by DanThrane** [comment]
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/d6905152-56d5-4949-b891-ea1f6467b4f2">

Text on role buttons are hard to read. For some reason the avatar of the invited user is significantly larger than the rest.

**Comment by DanThrane** [comment]
#3898 

Steps to reproduce:

- Create a folder called "3898test"
- In the same directory, create the same folder again
- The UI will now report that "3898test" and "3898test (1)" exist. Reloading the page will reveal that only "3898test" exists.

**Comment by Tiggles** [comment]
Closing. Further work in #4095
