### ISSUE TITLE
(More, pt II) UI-redesign issues

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#4095]
- [x] [VERY ESSENTIAL] Add DeiC logo after login page
- [x] [essential] #4094 
- [x] [essential] Drag to select (ResourceBrowser) should be activated on text drag, not on entire title row.
- [x] [essential] ResourceBrowser sometimes expands it's width quite a few times (https://github.com/SDU-eScience/UCloud/issues/4050#issuecomment-1808372619)
- [x] [essential] List of resource allocations does not refresh when changing project on Dashboard. (it does for me, but I don't think I've changed anything)
- [x] [essential] Application Studio buttons are invisible in light theme
- [x] [essential] Can navigate to unaccepted shares (https://github.com/sdu-eScience/uCloud/issues/4095#issuecomment-1862316495)
- [x] [essential] Positioning of prefix and postfix for resource-creation is off
- [x] [essential] Product-Selector positioning in ResourceBrowser is offset due to removed checkbox.
- [x] [essential] Move folder-mounting higher up
- [x] [essential] Importing JobParameters doesn't close the modal
- [x] [essential] Browse components hijacked refresh functions on dashboard
- [x] [essential] Implement this for this branch (118e30b83a310a64a7d44958313a784fbe1865e3)
- [x] [essential] Member-issues (https://github.com/SDU-eScience/UCloud/issues/4050#issuecomment-1825222532)
- [x] [essential] Currently no way to accept project invite
- [x] [essential] Users can't leave projects unless they are admins or PIs
- [x] [essential] cache for auto-complete seems to fetch "My workspace" drives, even with active project
- [x] [essential] crash on uploading files 
- [x] [essential] Drag-to-select does not work well in Safari. Likely `user-select` support.
- [x] [essential] Uploader styling
- [x] [essential] Ensure sidebar animation works in both directions
- [x] [essential] Add highlighted sidebar icon based on viewed page
- [x] [essential] Mutation warning for app-favorites (https://github.com/sdu-eScience/uCloud/issues/4095#issuecomment-1929285437)
- [x] [essential] Make ssh access a link. E.g. `ssh ucloud@ssh.cloud.sdu.dk -p 1234` -> `ssh://ssh ucloud@ssh.cloud.sdu.dk:2436` (EDIT: Anchor tag strips the username)
- [x] [essential] User can't create folder in folder-selector modal
- [x] [essential] Re-introduce `xterm` for Job's node outputs to properly handle escape codes.
- [x] [minor] You can't move or copy files when viewing job output folder
- [x] [minor] Add share invites to dashboard
- [x] [minor] Keyboard shortcuts are triggered when entering a name into share modal
- [x] [minor] When resource-browser is in search-mode, filebrowser breadcrumbs are still clickable
- [x] [minor] Sharing fails silently
- [x] [minor] Selecting multiple terminated jobs and opening the context-menu is non-empty, but operation has no text or icon (it does, it's just hard to see) (https://github.com/SDU-eScience/UCloud/issues/4095#issuecomment-1865971297)
- [x] [minor] Flicker in sidebar when viewing apps or runs.
- [x] [minor] Drives in sidebar are not shown as shares, when they are
- [x] [minor] Different heights for locationbar in different modes
- [x] [minor] You can navigate to drive being created (Arrow down, enter)

**Comment by xiroV** [comment]
- [ ] #4096

**Comment by xiroV** [comment]
- [ ] List of resource allocations does not refresh when changing project on Dashboard.

**Comment by DanThrane** [comment]
After having activated the navigation bar, it is impossible to change the position of the cursor using the mouse. I think we should change it such that only clicks outside of the box deactivates it.
<img width="1425" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/90ec952a-0455-4a87-9cef-5c5e0fa160a2">

**Comment by DanThrane** [comment]
Double-clicking an unaccepted share takes you to the shared file. This will always fail since you haven't accepted the file, yet. 
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/e2b736bc-81bf-4157-b7aa-7d28d9a0e030">
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/bb2a533a-36a0-4e43-ac1a-2adc439f220c">

**Comment by DanThrane** [comment]
Visible scrollbar causing issues in dark mode 
![image](https://github.com/SDU-eScience/UCloud/assets/1782437/6df2dfc4-9292-418a-94ec-5be6eb93d13f)

**Comment by Tiggles** [comment]
> Visible scrollbar causing issues in dark mode (and light mode, but less noticeable) ![image](https://private-user-images.githubusercontent.com/1782437/292112907-6df2dfc4-9292-418a-94ec-5be6eb93d13f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDkyMTEsIm5iZiI6MTcwMzE0ODkxMSwicGF0aCI6Ii8xNzgyNDM3LzI5MjExMjkwNy02ZGYyZGZjNC05MjkyLTQxOGEtOTRlYy01YmU2ZWI5M2QxM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDg1NTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJhY2E1MDBhOWM2MzIyYWYxMGZjYmRhNjBhZDJlZTA1Y2NlYWFkYmY0Y2YyMDM3NTI1NmQzNjBiZTNiM2NhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9voI20qd96ptol2YbCtg_tnP3RsaFE6BN7P9pTylijw)

Is this MacOS/FireFox?

**Comment by Tiggles** [comment]
Selecting multiple terminated jobs and opening the context-menu is non-empty, but operation has no text or icon
<img width="789" alt="Screenshot 2023-12-21 at 10 53 02" src="https://github.com/SDU-eScience/UCloud/assets/7610257/9f3b3fd2-6d28-46fc-86df-7a9531e4b4de">

**Comment by DanThrane** [comment]
Drag-to-select does not work well in Safari. It appears that the current `user-select: none` does not work correctly.
