### ISSUE TITLE
(Part II of More Part 2 of Part 2) UI redesign issues 

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#4177]
- [x] Drives can't be created for projects if on initial load
- [x] The header still lives for non-authenticated users (SKUs, for instance)
- [ ] #4198
- [x] Close contextmenu on activating in-header operation
- [x] Some user-facing references to "workspace" remain (should be "project")
- [x] Error background and text are both the same red color
- [ ] #4200
- [x] ["Search in you sub-projects" input field has issues consuming "E"](https://github.com/SDU-eScience/UCloud/issues/4177#issuecomment-2098235795)
- [ ] #4201
- [x] [How to clear a download row should be clearer](https://github.com/SDU-eScience/UCloud/issues/4177#issuecomment-2092565996)
- [x] [Add "Clear all finished" functionality to uploader](https://github.com/SDU-eScience/UCloud/issues/4177#issuecomment-2092565996)
- [x] [Setup Sync operation is missing provider](https://github.com/SDU-eScience/UCloud/issues/4177#issuecomment-2097932909)
- [x] [Missing drive number causes issues](https://github.com/sdu-eScience/uCloud/issues/4177#issuecomment-2092902751)
- [x] [Rigid text in thin buttons](https://github.com/sdu-eScience/uCloud/issues/4177#issuecomment-2095802455)
- [x] Usage Page should sort charts by priority
- [x] Leaving project has no prompt and happens instantly
- [x] [ResourceBrowser rows can be selected when creating entry](https://github.com/sdu-escience/ucloud/issues/4177#issuecomment-2074647019) (Bug introduced with clearing selection with outside click)
- [ ] #4199
- [x] [ConfirmationButton styling is inconsistent](https://github.com/sdu-eScience/uCloud/issues/4177#issuecomment-2085150392)
- [x] Remove / at end of routes
- [x] [Member view from a user's view only shows User and PI, not Admins](https://github.com/sdu-eScience/uCloud/issues/4177#issuecomment-2085339927)
- [x] Change 'workspace' to 'project', and allocations to subprojects
- [x] Show archived projects in context menu
- [x] Disabled project archiving
- [x] [Drag to move has confusing behavior when leaving rows](https://github.com/sdu-eScience/ucloud/issues/4177#issuecomment-2078888729)
- [x] DriveBrowse does not correctly disable/enable creation when changing projects
- [x] Drag-selection can be deselected when moving outside of component
- [x] Terminal theme colors don't match background colors anymore
- [x] Embedded FileBrowsers have short locationbar (See output files from job)
- [x] Grant Application - Enlargen provider text
- [x] Grant Application - Title and description should be above textarea-boxes in 'application' area
- [x] Remove drive id in location bar
- [x] "Delete" button propagates up from ContextSwitcher. Can delete selected files.
- [x] FolderIcon has some extra size to right, below and above

**Comment by Tiggles** [comment]
Previous #4141

**Comment by Tiggles** [comment]
<img width="1411" alt="Screenshot 2024-04-24 at 12 33 34" src="https://github.com/SDU-eScience/UCloud/assets/7610257/880430c9-3aed-43bc-a18b-10f142a5e769">

**Comment by Tiggles** [comment]
Drag to move has confusing behaviour when leaving rows
https://github.com/SDU-eScience/UCloud/assets/7610257/9d53ae4f-08d4-4b62-ab5f-cc767deb4652

**Comment by DanThrane** [comment]
<img width="960" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/88131c6b-7db0-4409-9843-59f1e0ee0f46">

Terminal background (definitely in light mode, maybe also dark) no longer matches the background. I suggest we simply update the terminal theme to match the background color(s) of the theme.

**Comment by Tiggles** [comment]
> Sometimes (but not always) when terminating a job, the checkmark that appears after pressing and holding the 'Stop application' button is mis-aligned with the background circle. <img alt="Skærmbillede 2024-04-30 kl 13 59 39" width="573" src="https://private-user-images.githubusercontent.com/33627730/326795691-ab08ac9f-c6bc-42e8-9019-bce38ac58293.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Nzg5NDcsIm5iZiI6MTcxNDQ3ODY0NywicGF0aCI6Ii8zMzYyNzczMC8zMjY3OTU2OTEtYWIwOGFjOWYtYzZiYy00MmU4LTkwMTktYmNlMzhhYzU4MjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEyMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMDQ0MjM2MTQ4YzM1ZDg2ZTkxYzU4YWY4MjUxMzE3NjRjYmY1NmJkOGI2NDFjOGE0M2NmODYzMTE1M2ZjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wN_a7nr6faU7auDshycZifjZqeFDlZPxGQT7ZwfGR4g">

If you move you mouse outside, you miscolored circle should appear

**Comment by Tiggles** [comment]
Member view from a user's view only shows User and PI, not Admins
<img width="710" alt="Screenshot 2024-04-30 at 14 58 06" src="https://github.com/SDU-eScience/UCloud/assets/7610257/1a759aa3-5971-4f0b-a300-e013694d0afe">

**Comment by hschu12** [comment]
The remove finished upload by clicking checkmark is not intuitive. Only found out by coincidence. 
Would also be nice with a "clear all" option.

<img width="655" alt="Screenshot 2024-05-03 at 10 36 46" src="https://github.com/SDU-eScience/UCloud/assets/10943804/7a28f67d-edf5-4f62-95cc-b511ba4fadfe">

**Comment by hschu12** [comment]
Upload only allows me to upload folders by drag and drop. Cannot be selected by pop up file browser
<img width="866" alt="Screenshot 2024-05-03 at 10 57 46" src="https://github.com/SDU-eScience/UCloud/assets/10943804/cb1e2a79-e024-42f5-9eba-7d8c7c21dce9">

**Comment by DanThrane** [comment]
> Upload only allows me to upload folders by drag and drop. Cannot be selected by pop up file browser <img alt="Screenshot 2024-05-03 at 10 57 46" width="866" src="https://private-user-images.githubusercontent.com/10943804/327702855-cb1e2a79-e024-42f5-9eba-7d8c7c21dce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzU2MDUsIm5iZiI6MTcxNDczNTMwNSwicGF0aCI6Ii8xMDk0MzgwNC8zMjc3MDI4NTUtY2IxZTJhNzktZTAyNC00MmY1LTllYmEtN2Q4YzdjMjFkY2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDExMjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlY2ViNTg4ZWQ0ZDAyZjE0MGVjYmM3ODBlY2MwNjgxOTQ0OGJlZWJiNDQyZjkzNTc4YzIzZWU3ZDQ1ZjgyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ecSTcn2Zxdx9GzRDc4JUgiH7CF9YCuzfUJOp3bBqd6g">

Not supposed to. Admittedly, this is only the case because the browser doesn't allow us to do both in a nice way.

**Comment by hschu12** [comment]
Clicking the "Apply for Ressources" in the sidebar while looking at an already submittet grant it does reset the grant page. Only the URL is set to as being a new grant allocation.

<img width="1611" alt="Screenshot 2024-05-03 at 13 51 44" src="https://github.com/SDU-eScience/UCloud/assets/10943804/e2f0c4f3-c1f6-4b8b-9fb2-7574f9201487">

**Comment by hschu12** [comment]
Nice to have: Switch the "Launch with" to "Empty trash" when only Trash is selected. Insted of having to find the option in the ellipsis.

<img width="1345" alt="Screenshot 2024-05-03 at 14 02 26" src="https://github.com/SDU-eScience/UCloud/assets/10943804/28bf5b76-3491-4214-b566-296fddc63e32">

**Comment by hschu12** [comment]
Path copy and pasting does not work after number was removed. Need to be rolled back.
<img width="1522" alt="Screenshot 2024-05-03 at 14 12 13" src="https://github.com/SDU-eScience/UCloud/assets/10943804/c5afbd9a-b65a-4b9e-bb12-c6d7d387768c">
<img width="1441" alt="Screenshot 2024-05-03 at 14 12 18" src="https://github.com/SDU-eScience/UCloud/assets/10943804/bd356b29-c4ef-4943-bd9a-8472e6b05d21">

**Comment by mrlhansen** [comment]
Because we still have this issue with reloading pages whose URL ends in a `/` lets at least remove the slash from all links.
* Change link for "Drives" in primary sidebar from https://dev.cloud.sdu.dk/app/drives/ to https://dev.cloud.sdu.dk/app/drives
* Change link for "Project settings" in secondary sidebar from https://dev.cloud.sdu.dk/app/project/settings/ to https://dev.cloud.sdu.dk/app/project/settings
* Change link for "Jobs" in primary sidebar from https://dev.cloud.sdu.dk/app/jobs/ to https://dev.cloud.sdu.dk/app/jobs

**Comment by mrlhansen** [comment]
Related to above, the link to files here is broken: 
![image](https://github.com/SDU-eScience/UCloud/assets/31279460/3b9d46a3-fbd6-4999-a57d-b7f74c4e9b45)

**Comment by mrlhansen** [comment]
On the dashboard the pop out link for recent runs also has a slash in the link:
![image](https://github.com/SDU-eScience/UCloud/assets/31279460/703def9f-abeb-46a0-a273-437df0146ccb)

**Comment by Tiggles** [comment]
> When using the shortcut ⌘+A to select all files in a folder with many files, only a subset of the files are actually selected.

How many files do you have? Tested with 1455 files without issue.

**Comment by mrlhansen** [comment]
Pressing "Sync setup" makes the page jump back to the list of drives.
![image](https://github.com/SDU-eScience/UCloud/assets/31279460/33cb9f2a-a17b-41c6-bf59-e73870c267da)

**Comment by DanThrane** [comment]
The 'e' key doesn't work in the "search sub-projects" field (it is almost definitely being consumed by the "edit" shortcut, we shouldn't propagate from the input field to avoid this).

**Comment by DanThrane** [comment]
> > > When using the shortcut ⌘+A to select all files in a folder with many files, only a subset of the files are actually selected.
> > 
> > 
> > How many files do you have? Tested with 1455 files without issue.
> 
> I have >15000 files in the folders in question.

@Tiggles There is a small chance this only triggers with more than 10000 files, but that is just a guess. We are currently pre-fetching 10000 files eagerly.

**Comment by Tiggles** [comment]
> > > > When using the shortcut ⌘+A to select all files in a folder with many files, only a subset of the files are actually selected.
> > > 
> > > 
> > > How many files do you have? Tested with 1455 files without issue.
> > 
> > 
> > I have >15000 files in the folders in question.
> 
> @Tiggles There is a small chance this only triggers with more than 10000 files, but that is just a guess. We are currently pre-fetching 10000 files eagerly.

So do we accept this limitation, or should we change the code to make it work?

**Comment by Tiggles** [comment]
<img width="556" alt="Screenshot 2024-05-07 at 14 58 22" src="https://github.com/SDU-eScience/UCloud/assets/7610257/5380cffe-0601-4f1c-9c66-d8f71e53953f">

Confusing error message for end-user
