### ISSUE TITLE
Copy-on-Write Filesystems for Applications

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#976]
SDUCloud needs a proper copy-on-write (CoW) solution for applications. We need this for when an application mounts a folder. 

The SDUCloud file system is a managed file system. This means that we must be able to track every operation which occurs on a given file.

Inside of an application we have no good way to track the changes to a file. This is a consequence of allowing users to run any container. The user is also allowed to run as root within the container, complicating the issue further. As a result, the file system mounted inside of an application is about as unmanaged as it gets. __This means that we cannot perform a direct mount of the CephFS.__

To solve this we perform file system management at certain checkpoints. The system performs authorisation checks at the beginning and end of an application. All changes to the filesystem are not visible until the end of an application.

SDUCloud implements this in the 'workspace' feature of the storage service. The workspace feature creates a copy of the filesystem, after authorisation has passed. The copy of the filesystem is then mounted by the application. The system merges the two filesystems at the end.

The implementation strategy used is quite slow. Copying all the files ahead of times takes a lot of time. Using a CoW filesystem would give a significant boost to startup time.

The general idea is that we use a CoW filesystem with a read-only lower layer of the real filesystem. The lower layer could be a frozen snapshot (as supported by CephFS). The upper layer would live inside of the container. At the end of the application we can take changes from the upper layer and apply them to the real filesystem.

Several CoWs already exists on the market. Below is an incomplete list:

- Aufs
- UnionFS
- OverlayFS

The CoW we use needs to support our version of CephFS. Most of these support it in theory. Yet, our attempts so far have shown poor results. Results so far has ranged from it not working (operation not supported) to kernel panics. Not a single one of these has worked so far.

Below is a list of things we should attempt:

- [x] Upgrade the Ceph system on the dev environ to same version as prod
- [x] Make sure the dev system runs the same kernel and OS as the prod system
- [x] Try to find alternatives
